FAKEDEVICES = {
    "cmissed": [
        {"phone_number": "**REDACTED**", "date": "**REDACTED**", "callId": "1"}
    ],
    "devices": {
        "48:E1:E9:A2:62:67": {
            "Key": "48:E1:E9:A2:62:67",
            "DiscoverySource": "import",
            "Name": "meross-mss210-6267",
            "DeviceType": "AC Outlet",
            "Active": True,
            "Tags": "lan edev mac physical wifi flowstats ipv4 ipv6 dhcp ssw_sta mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T13:39:03Z",
            "LastChanged": "2025-08-31T13:39:03Z",
            "Master": "",
            "VendorClassID": "",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,28,6]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl0",
            "InterfaceName": "vap2g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -43,
            "SignalNoiseRatio": 51,
            "LastDataDownlinkRate": 72222,
            "LastDataUplinkRate": 65000,
            "EncryptionMode": "AES",
            "LinkBandwidth": "20MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "SGI20",
            "VhtCapabilities": "",
            "HeCapabilities": "",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "n",
            "OperatingFrequencyBand": "2.4GHz",
            "AvgSignalStrengthByChain": -43,
            "MaxBandwidthSupported": "20MHz",
            "MaxDownlinkRateSupported": 72222,
            "MaxDownlinkRateReached": 72222,
            "DownlinkMCS": 7,
            "DownlinkBandwidth": 20,
            "DownlinkShortGuard": True,
            "UplinkMCS": 7,
            "UplinkBandwidth": 20,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 72222,
            "MaxUplinkRateReached": 65000,
            "MaxTxSpatialStreamsSupported": 1,
            "MaxRxSpatialStreamsSupported": 1,
            "Index": "5",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "5",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "meross-mss210-6267",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "meross-mss210-6267",
                    "Source": "mdns",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "meross-mss210",
                    "Source": "webui",
                    "Suffix": "6267",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "AC Outlet", "Source": "webui", "Id": "**REDACTED**"}
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "mDNSService": [],
            "mDNSRecord": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211w",
                "Supports24GHz": True,
                "Supports5GHz": False,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 0,
                "AvgSteeringTime": 0,
                "SupportedUNIIBands": "",
                "VendorSpecificElementOUIList": "00:50:F2",
                "SupportedRadioStandards": "b,g,n",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
        },
        "DC:6A:E7:1B:97:F3": {
            "Key": "DC:6A:E7:1B:97:F3",
            "DiscoverySource": "import",
            "Name": "Xiaomi-13-1",
            "DeviceType": "Mobile",
            "Active": True,
            "Tags": "lan edev mac physical flowstats wifi ipv4 ipv6 dhcp android ssw_sta vowifi mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T15:57:07Z",
            "LastChanged": "2025-08-31T15:57:13Z",
            "Master": "",
            "VendorClassID": "android-dhcp-15",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,15,26,28,51,58,59,43,114,108]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl1",
            "InterfaceName": "vap5g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -85,
            "SignalNoiseRatio": 7,
            "LastDataDownlinkRate": 408330,
            "LastDataUplinkRate": 6000,
            "EncryptionMode": "AES",
            "LinkBandwidth": "160MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "SGI80,SGI160,SU-BFR,SU-BFE,MU-BFE",
            "HeCapabilities": "SU-BFR,SU&MU-BFE",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "be",
            "OperatingFrequencyBand": "5GHz",
            "AvgSignalStrengthByChain": -85,
            "MaxBandwidthSupported": "160MHz",
            "MaxDownlinkRateSupported": 2401911,
            "MaxDownlinkRateReached": 2450000,
            "DownlinkMCS": 4,
            "DownlinkBandwidth": 160,
            "DownlinkShortGuard": False,
            "UplinkMCS": 3,
            "UplinkBandwidth": 20,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 2401911,
            "MaxUplinkRateReached": 1921540,
            "MaxTxSpatialStreamsSupported": 2,
            "MaxRxSpatialStreamsSupported": 2,
            "Index": "6",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "6",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Xiaomi-13",
                    "Source": "dhcp",
                    "Suffix": "1",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Xiaomi-13",
                    "Source": "webui",
                    "Suffix": "1",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Mobile", "Source": "dhcp", "Id": "**REDACTED**"},
                {"Type": "Mobile", "Source": "webui", "Id": "**REDACTED**"},
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211v,80211w",
                "Supports24GHz": True,
                "Supports5GHz": True,
                "Supports6GHz": True,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 0,
                "AvgSteeringTime": 0,
                "SupportedUNIIBands": "U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4,U-NII-5,U-NII-6,U-NII-7,U-NII-8",
                "VendorSpecificElementOUIList": "00:50:F2,8C:FD:F0,8C:BE:BE,50:6F:9A",
                "SupportedRadioStandards": "a,n,ac,ax,be",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 2,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [
                    {
                        "APName": "vap5g0priv",
                        "MACAddress": "**REDACTED**",
                        "FrequencyBand": "5GHz",
                        "SignalStrength": -84,
                        "AvgSignalStrengthByChain": 0,
                        "MaxBandwidthSupported": "",
                        "Id": "**REDACTED**",
                    },
                    {
                        "APName": "vap2g0priv",
                        "MACAddress": "**REDACTED**",
                        "FrequencyBand": "2.4GHz",
                        "SignalStrength": -200,
                        "AvgSignalStrengthByChain": 0,
                        "MaxBandwidthSupported": "",
                        "Id": "**REDACTED**",
                    },
                ],
            },
            "mDNSService": [],
            "mDNSRecord": [],
        },
        "28:C2:DD:8C:6A:1F": {
            "Key": "28:C2:DD:8C:6A:1F",
            "DiscoverySource": "import",
            "Name": "Famille-PC",
            "DeviceType": "Computer",
            "Active": False,
            "Tags": "lan edev mac physical ipv4 ipv6 dhcp flowstats microsoft wifi ssw_sta mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-30T15:26:58Z",
            "LastChanged": "2025-08-31T13:05:14Z",
            "Master": "",
            "VendorClassID": "MSFT 5.0",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,15,31,33,43,44,46,47,119,121,249,252]",
            "IPAddress": "",
            "IPAddressSource": "",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl0",
            "InterfaceName": "vap2g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": 0,
            "SignalNoiseRatio": 0,
            "LastDataDownlinkRate": 0,
            "LastDataUplinkRate": 0,
            "EncryptionMode": "",
            "LinkBandwidth": "",
            "SecurityModeEnabled": "",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "",
            "HeCapabilities": "",
            "SupportedMCS": "",
            "AuthenticationState": False,
            "OperatingStandard": "",
            "OperatingFrequencyBand": "",
            "AvgSignalStrengthByChain": 0,
            "MaxBandwidthSupported": "",
            "MaxDownlinkRateSupported": 0,
            "MaxDownlinkRateReached": 0,
            "DownlinkMCS": 0,
            "DownlinkBandwidth": 0,
            "DownlinkShortGuard": False,
            "UplinkMCS": 0,
            "UplinkBandwidth": 0,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 0,
            "MaxUplinkRateReached": 0,
            "MaxTxSpatialStreamsSupported": 1,
            "MaxRxSpatialStreamsSupported": 1,
            "Index": "7",
            "Actions": [
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "7",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Famille-PC",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Famille-PC",
                    "Source": "mdns",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Famille-PC",
                    "Source": "webui",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Famille-PC",
                    "Source": "dns",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Computer", "Source": "default", "Id": "**REDACTED**"}
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "not reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211v,80211w",
                "Supports24GHz": True,
                "Supports5GHz": False,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 0,
                "AvgSteeringTime": 0,
                "SupportedUNIIBands": "",
                "VendorSpecificElementOUIList": "00:50:F2",
                "SupportedRadioStandards": "b,g,n",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
            "mDNSService": [],
            "mDNSRecord": [],
        },
        "6C:0B:5E:D6:8B:B3": {
            "Key": "6C:0B:5E:D6:8B:B3",
            "DiscoverySource": "import",
            "Name": "HPID68BAA",
            "DeviceType": "Printer",
            "Active": False,
            "Tags": "lan edev mac physical ipv4 ipv6 flowstats dhcp wifi ssw_sta mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-04T17:41:50Z",
            "LastChanged": "2025-08-31T13:05:14Z",
            "Master": "",
            "VendorClassID": "",
            "UserClassID": "",
            "ClientID": "",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "",
            "IPAddress": "",
            "IPAddressSource": "",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "",
            "InterfaceName": "",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": 0,
            "SignalNoiseRatio": 0,
            "LastDataDownlinkRate": 0,
            "LastDataUplinkRate": 0,
            "EncryptionMode": "",
            "LinkBandwidth": "",
            "SecurityModeEnabled": "",
            "HtCapabilities": "",
            "VhtCapabilities": "",
            "HeCapabilities": "",
            "SupportedMCS": "",
            "AuthenticationState": False,
            "OperatingStandard": "",
            "OperatingFrequencyBand": "",
            "AvgSignalStrengthByChain": 0,
            "MaxBandwidthSupported": "",
            "MaxDownlinkRateSupported": 0,
            "MaxDownlinkRateReached": 0,
            "DownlinkMCS": 0,
            "DownlinkBandwidth": 0,
            "DownlinkShortGuard": False,
            "UplinkMCS": 0,
            "UplinkBandwidth": 0,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 0,
            "MaxUplinkRateReached": 0,
            "MaxTxSpatialStreamsSupported": 0,
            "MaxRxSpatialStreamsSupported": 0,
            "Index": "8",
            "Actions": [
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "8",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "HP;Typ=MFP;HP OfficeJet Pro 8120e series;TH51UKP184;",
                    "Source": "UserClassID",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "HPID68BAA",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "BRW046874F214C6",
                    "Source": "mdns",
                    "Suffix": "1",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "HPID68BAA",
                    "Source": "webui",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Printer", "Source": "webui", "Id": "**REDACTED**"}
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "mDNSService": [],
            "mDNSRecord": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "",
                "Supports24GHz": False,
                "Supports5GHz": False,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 0,
                "AvgSteeringTime": 0,
                "SupportedUNIIBands": "",
                "VendorSpecificElementOUIList": "",
                "SupportedRadioStandards": "",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
        },
        "A4:E2:87:06:FA:09": {
            "Key": "A4:E2:87:06:FA:09",
            "DiscoverySource": "import",
            "Name": "Xiaomi-Pad-6",
            "DeviceType": "Tablet Android",
            "Active": True,
            "Tags": "lan edev mac physical wifi flowstats ipv4 ipv6 dhcp android ssw_sta events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T13:39:16Z",
            "LastChanged": "2025-08-31T13:40:06Z",
            "Master": "",
            "VendorClassID": "android-dhcp-14",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,15,26,28,51,58,59,43,114,108]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl1",
            "InterfaceName": "vap5g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -84,
            "SignalNoiseRatio": 8,
            "LastDataDownlinkRate": 720580,
            "LastDataUplinkRate": 288230,
            "EncryptionMode": "AES",
            "LinkBandwidth": "80MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "SGI80,SU-BFE,MU-BFE",
            "HeCapabilities": "SU&MU-BFE",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "ax",
            "OperatingFrequencyBand": "5GHz",
            "AvgSignalStrengthByChain": -84,
            "MaxBandwidthSupported": "80MHz",
            "MaxDownlinkRateSupported": 866666,
            "MaxDownlinkRateReached": 816660,
            "DownlinkMCS": 7,
            "DownlinkBandwidth": 80,
            "DownlinkShortGuard": False,
            "UplinkMCS": 3,
            "UplinkBandwidth": 80,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 866666,
            "MaxUplinkRateReached": 576470,
            "MaxTxSpatialStreamsSupported": 2,
            "MaxRxSpatialStreamsSupported": 2,
            "Index": "9",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "9",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Xiaomi-Pad-6",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Xiaomi-Pad",
                    "Source": "webui",
                    "Suffix": "6",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Tablet Android", "Source": "webui", "Id": "**REDACTED**"},
                {"Type": "Mobile", "Source": "dhcp", "Id": "**REDACTED**"},
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211v,80211w",
                "Supports24GHz": True,
                "Supports5GHz": True,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 3,
                "AvgSteeringTime": 1056,
                "SupportedUNIIBands": "U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4",
                "VendorSpecificElementOUIList": "",
                "SupportedRadioStandards": "a,b,g,n,ac,ax",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
        },
        "30:A9:DE:7E:CC:1E": {
            "Key": "30:A9:DE:7E:CC:1E",
            "DiscoverySource": "import",
            "Name": "LGwebOSTV",
            "DeviceType": "TV",
            "Active": True,
            "Tags": "lan edev mac physical wifi flowstats ipv4 ipv6 dhcp upnp ssw_sta lg tv events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T15:49:06Z",
            "LastChanged": "2025-08-31T15:49:09Z",
            "Master": "",
            "VendorClassID": "",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[252,3,42,15,6,1,12]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl0",
            "InterfaceName": "vap2g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -65,
            "SignalNoiseRatio": 29,
            "LastDataDownlinkRate": 115556,
            "LastDataUplinkRate": 144444,
            "EncryptionMode": "AES",
            "LinkBandwidth": "20MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "SGI80,SU-BFR,SU-BFE",
            "HeCapabilities": "",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "n",
            "OperatingFrequencyBand": "2.4GHz",
            "AvgSignalStrengthByChain": -65,
            "MaxBandwidthSupported": "20MHz",
            "MaxDownlinkRateSupported": 144444,
            "MaxDownlinkRateReached": 144444,
            "DownlinkMCS": 13,
            "DownlinkBandwidth": 20,
            "DownlinkShortGuard": True,
            "UplinkMCS": 15,
            "UplinkBandwidth": 20,
            "UplinkShortGuard": True,
            "MaxUplinkRateSupported": 144444,
            "MaxUplinkRateReached": 144444,
            "MaxTxSpatialStreamsSupported": 2,
            "MaxRxSpatialStreamsSupported": 2,
            "Index": "10",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "10",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "LGwebOSTV",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "TV", "Source": "dhcp", "Id": "**REDACTED**"},
                {
                    "Type": "MediaRenderer",
                    "Source": "upnp-uuid:5b552c91-aaf9-0d9f-3635-d9ba09b8c602",
                    "Id": "**REDACTED**",
                },
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": False,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "",
                "Supports24GHz": True,
                "Supports5GHz": True,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 0,
                "AvgSteeringTime": 0,
                "SupportedUNIIBands": "Unknown,U-NII-1,U-NII-2A,U-NII-2C",
                "VendorSpecificElementOUIList": "00:90:4C,00:10:18,00:50:F2",
                "SupportedRadioStandards": "a,b,g,n,ac",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
        },
        "00:C3:0A:AA:98:87": {
            "Key": "00:C3:0A:AA:98:87",
            "DiscoverySource": "import",
            "Name": "Xiaomi-12T-Pro",
            "DeviceType": "Mobile",
            "Active": True,
            "Tags": "lan edev mac physical wifi flowstats ipv4 ipv6 dhcp android ssw_sta vowifi mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T14:31:01Z",
            "LastChanged": "2025-08-31T14:31:12Z",
            "Master": "",
            "VendorClassID": "android-dhcp-15",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,15,26,28,51,58,59,43,114,108]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl1",
            "InterfaceName": "vap5g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -76,
            "SignalNoiseRatio": 16,
            "LastDataDownlinkRate": 1441170,
            "LastDataUplinkRate": 864700,
            "EncryptionMode": "AES",
            "LinkBandwidth": "160MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "SGI80,SGI160,SU-BFR,SU-BFE,MU-BFE",
            "HeCapabilities": "SU-BFR,SU&MU-BFE",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "ax",
            "OperatingFrequencyBand": "5GHz",
            "AvgSignalStrengthByChain": -76,
            "MaxBandwidthSupported": "160MHz",
            "MaxDownlinkRateSupported": 2401911,
            "MaxDownlinkRateReached": 2161760,
            "DownlinkMCS": 7,
            "DownlinkBandwidth": 160,
            "DownlinkShortGuard": False,
            "UplinkMCS": 4,
            "UplinkBandwidth": 160,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 2401911,
            "MaxUplinkRateReached": 2401910,
            "MaxTxSpatialStreamsSupported": 2,
            "MaxRxSpatialStreamsSupported": 2,
            "Index": "12",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "12",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Xiaomi-12T-Pro",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Android_7DHVUQ18",
                    "Source": "mdns",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [{"Type": "Mobile", "Source": "dhcp", "Id": "**REDACTED**"}],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211v,80211u,80211w",
                "Supports24GHz": True,
                "Supports5GHz": True,
                "Supports6GHz": False,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 6,
                "AvgSteeringTime": 978,
                "SupportedUNIIBands": "Unknown,U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4",
                "VendorSpecificElementOUIList": "00:50:F2,8C:FD:F0,8C:BE:BE,50:6F:9A",
                "SupportedRadioStandards": "a,b,g,n,ac,ax",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
            "mDNSService": [],
            "mDNSRecord": [],
        },
        "40:1C:83:3C:A0:37": {
            "Key": "40:1C:83:3C:A0:37",
            "DiscoverySource": "import",
            "Name": "Device-59",
            "DeviceType": "Computer",
            "Active": True,
            "Tags": "lan edev mac physical eth flowstats ipv4 ipv6 events",
            "FirstSeen": "2025-08-23T18:34:10Z",
            "LastConnection": "2025-08-31T13:05:21Z",
            "LastChanged": "2025-08-31T13:05:34Z",
            "Master": "",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "Static",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "eth1",
            "InterfaceName": "ETH3",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "Index": "59",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "59",
                    "Id": "**REDACTED**",
                }
            ],
            "DeviceTypes": [
                {"Type": "Computer", "Source": "default", "Id": "**REDACTED**"}
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "Static",
                    "Reserved": False,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
        },
        "8C:9A:8F:64:9A:D8": {
            "Key": "8C:9A:8F:64:9A:D8",
            "DiscoverySource": "bridge",
            "Name": "PC_MLTV_WHD95",
            "DeviceType": "Set-top Box",
            "Active": True,
            "Tags": "lan edev mac physical eth flowstats ipv4 ipv6 dhcp stb orange power_state upnp information green manageable events",
            "FirstSeen": "2025-08-23T19:13:08Z",
            "LastConnection": "2025-08-31T15:48:47Z",
            "LastChanged": "2025-08-31T15:48:50Z",
            "Master": "",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "eth2",
            "InterfaceName": "ETH2",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "VendorClassID": "sagem",
            "UserClassID": "PC_MLTV_WHD95",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,7,12,15,28,33,42,43,72,121,125]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "HardwareVersion": "",
            "PowerState": "On",
            "ModelName": "",
            "OperatingSystem": "unknown",
            "SoftwareVersion": "",
            "Manufacturer": "",
            "DeviceCategory": "unknown",
            "CatalogID": "",
            "Index": "102",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "102",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "PC_MLTV_WHD95",
                    "Source": "UserClassID",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "Decodeur TV Orange",
                    "Source": "upnp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Computer", "Source": "default", "Id": "**REDACTED**"},
                {"Type": "Set-top Box", "Source": "dhcp", "Id": "**REDACTED**"},
                {
                    "Type": "MediaRenderer",
                    "Source": "upnp-uuid:00ababad-7947-1048-8a00-8c9a8f649ad8",
                    "Id": "**REDACTED**",
                },
                {
                    "Type": "Basic",
                    "Source": "upnp-uuid:82621939-1259-54de-9d5c-1c70700a4d74",
                    "Id": "**REDACTED**",
                },
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": False,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "ModelNames": [],
            "OperatingSystems": [],
            "SoftwareVersions": [],
            "Manufacturers": [],
            "DeviceCategories": [],
            "CatalogIDs": [],
        },
        "04:7B:CB:B7:D2:AE": {
            "Key": "04:7B:CB:B7:D2:FF",
            "DiscoverySource": "import",
            "Name": "LAPTOP-TSA",
            "DeviceType": "Computer",
            "Active": True,
            "Tags": "lan edev mac physical wifi flowstats ssw_sta ipv4 ipv6 dhcp microsoft lltd mdns events",
            "FirstSeen": "2025-08-23T18:34:14Z",
            "LastConnection": "2025-08-31T13:39:00Z",
            "LastChanged": "2025-08-31T13:39:00Z",
            "Master": "",
            "VendorClassID": "MSFT 5.0",
            "UserClassID": "",
            "ClientID": "**REDACTED**",
            "SerialNumber": "",
            "ProductClass": "",
            "OUI": "",
            "DHCPOption55": "[1,3,6,15,31,33,43,44,46,47,119,121,249,252]",
            "IPAddress": "**REDACTED**",
            "IPAddressSource": "DHCP",
            "Location": "",
            "PhysAddress": "**REDACTED**",
            "Layer2Interface": "wl1",
            "InterfaceName": "vap5g0priv",
            "MACVendor": "",
            "Owner": "",
            "UniqueID": "**REDACTED**",
            "SignalStrength": -80,
            "SignalNoiseRatio": 12,
            "LastDataDownlinkRate": 1225000,
            "LastDataUplinkRate": 576470,
            "EncryptionMode": "AES",
            "LinkBandwidth": "160MHz",
            "SecurityModeEnabled": "WPA2-Personal",
            "HtCapabilities": "40MHz,SGI20,SGI40",
            "VhtCapabilities": "SGI80,SGI160,SU-BFE,MU-BFE",
            "HeCapabilities": "SU&MU-BFE",
            "SupportedMCS": "",
            "AuthenticationState": True,
            "OperatingStandard": "ax",
            "OperatingFrequencyBand": "5GHz",
            "AvgSignalStrengthByChain": -80,
            "MaxBandwidthSupported": "160MHz",
            "MaxDownlinkRateSupported": 2401911,
            "MaxDownlinkRateReached": 1361110,
            "DownlinkMCS": 6,
            "DownlinkBandwidth": 160,
            "DownlinkShortGuard": False,
            "UplinkMCS": 3,
            "UplinkBandwidth": 160,
            "UplinkShortGuard": False,
            "MaxUplinkRateSupported": 2401911,
            "MaxUplinkRateReached": 576470,
            "MaxTxSpatialStreamsSupported": 2,
            "MaxRxSpatialStreamsSupported": 2,
            "Index": "15",
            "Actions": [
                {
                    "Function": "setName",
                    "Name": "Edit Name",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "setType",
                    "Name": "Edit Type",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "source", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "startEventing",
                    "Name": "startEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True},
                        {"Name": "types", "Type": "string", "Mandatory": False},
                    ],
                },
                {
                    "Function": "stopEventing",
                    "Name": "stopEventing",
                    "Arguments": [
                        {"Name": "name", "Type": "string", "Mandatory": True}
                    ],
                },
                {
                    "Function": "getEventLog",
                    "Name": "getEventLog",
                    "Arguments": [
                        {"Name": "type", "Type": "string", "Mandatory": True},
                        {"Name": "since", "Type": "datetime", "Mandatory": False},
                        {"Name": "until", "Type": "datetime", "Mandatory": False},
                    ],
                },
                {"Function": "listLiveEventTypes", "Name": "listLiveEventTypes"},
                {"Function": "listLogEventTypes", "Name": "listLogEventTypes"},
                {"Function": "listEventSubscribers", "Name": "listEventSubscribers"},
            ],
            "Names": [
                {
                    "Name": "Device",
                    "Source": "default",
                    "Suffix": "15",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "LAPTOP-TSA",
                    "Source": "dhcp",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
                {
                    "Name": "LAPTOP-TSA",
                    "Source": "lltdmachinename",
                    "Suffix": "",
                    "Id": "**REDACTED**",
                },
            ],
            "DeviceTypes": [
                {"Type": "Computer", "Source": "default", "Id": "**REDACTED**"}
            ],
            "BDD": {
                "CloudVersion": "",
                "BDDRequestsSent": 0,
                "BDDRequestsAnswered": 0,
                "BDDRequestsFailed": 0,
                "BDDLastSyncTimestamp": "0001-01-01T00:00:00Z",
                "DeviceName": "",
                "DeviceType": "",
                "ModelName": "",
                "OperatingSystem": "",
                "SoftwareVersion": "",
                "Manufacturer": "",
                "MACVendor": "",
                "DeviceCategory": "",
                "PerformManualLookup": False,
            },
            "IPv4Address": [
                {
                    "Address": "**REDACTED**",
                    "Status": "reachable",
                    "Scope": "global",
                    "AddressSource": "DHCP",
                    "Reserved": True,
                    "Id": "**REDACTED**",
                }
            ],
            "IPv6Address": "**REDACTED**",
            "LLTD": {
                "ManagementURL": "",
                "PhysicalMedium": 0,
                "WirelessMode": 0,
                "BSSID": "",
                "SSID": "",
                "WirelessPhysicalMedium": 0,
                "MaxRate": 0,
                "LinkSpeed": 0,
                "RSSI": 0,
                "Support": "",
            },
            "Locations": [],
            "Groups": [],
            "Priority": {"Configuration": "Automatic", "Type": "BestEffort"},
            "SSWSta": {
                "SupportedStandards": "80211k,80211v,80211w",
                "Supports24GHz": True,
                "Supports5GHz": True,
                "Supports6GHz": True,
                "ReconnectClass": "",
                "FailedSteerCount": 0,
                "SuccessSteerCount": 4,
                "AvgSteeringTime": 3060,
                "SupportedUNIIBands": "Unknown,U-NII-1,U-NII-2A,U-NII-2C,U-NII-3,U-NII-4,U-NII-5,U-NII-6,U-NII-7,U-NII-8",
                "VendorSpecificElementOUIList": "50:6F:9A,00:50:F2,8C:FD:F0",
                "SupportedRadioStandards": "a,b,g,n,ac,ax",
                "SupportedMLOModes": "",
                "MaxNumberOfAffiliatedSta": 0,
            },
            "UserAgents": [],
            "WANAccess": {"BlockedReasons": ""},
            "WiFiStaStats": {
                "EhtCapabilities": "",
                "MLOMode": "Unknown",
                "OperatingFrequencyBandList": "",
                "AffiliatedSta": [],
            },
            "mDNSService": [],
            "mDNSRecord": [],
        },
    },
    "dsl_status": {},
    "infos": {
        "Manufacturer": "Sagemcom",
        "ManufacturerOUI": "78C213",
        "ModelName": "SagemcomFast5698_OFR",
        "Description": "SagemcomFast5698_OFR Sagemcom fr",
        "ProductClass": "Livebox W7",
        "SerialNumber": "**REDACTED**",
        "HardwareVersion": "SG_LBW7_27.3.0",
        "SoftwareVersion": "SGW7-fr-G03.R00.C02_02",
        "RescueVersion": "SGW7-fr-G02.R06.C03_00",
        "ModemFirmwareVersion": "",
        "EnabledOptions": "",
        "AdditionalHardwareVersion": "",
        "AdditionalSoftwareVersion": "sbl-G3.R0.C2-fr",
        "SpecVersion": "1.1",
        "ProvisioningCode": "**REDACTED**",
        "UpTime": 11870,
        "FirstUseDate": "0001-01-01T00:00:00Z",
        "DeviceLog": "",
        "VendorConfigFileNumberOfEntries": 1,
        "ManufacturerURL": "http://www.sagemcom.com/",
        "Country": "fr",
        "ExternalIPAddress": "**REDACTED**",
        "DeviceStatus": "Up",
        "NumberOfReboots": 4,
        "UpgradeOccurred": False,
        "ResetOccurred": False,
        "RestoreOccurred": False,
        "StandbyOccurred": False,
        "X_SOFTATHOME-COM_AdditionalSoftwareVersions": "Bootloader=proj_lb77_gen_2024.04_a1.0.16.0,RescueBootloader=proj_lb77_gen_2024.04_a1.0.16.0",
        "BaseMAC": "**REDACTED**",
    },
    "nmc": {
        "WanModeList": "Ethernet_PPP;Ethernet_DHCP;GPON_DHCP;GPON_PPP",
        "WanMode": "GPON_DHCP",
        "Username": "**REDACTED**",
        "FactoryResetScheduled": False,
        "ConnectionError": False,
        "DefaultsLoaded": True,
        "ProvisioningState": "done",
        "OfferType": "Res",
        "OfferName": "MonoLigne",
        "IPTVMode": "Internet",
    },
    "wan_status": {
        "WanState": "up",
        "LinkType": "gpon",
        "LinkState": "up",
        "GponState": "O5_Operation",
        "MACAddress": "**REDACTED**",
        "Protocol": "dhcp",
        "ConnectionState": "Bound",
        "LastConnectionError": "None",
        "IPAddress": "**REDACTED**",
        "RemoteGateway": "**REDACTED**",
        "DNSServers": "80.10.246.1,81.253.149.9,2a01:cfc4:2000:f::1,2a01:cfc4:2180:4001::2",
        "IPv6Address": "**REDACTED**",
        "IPv6DelegatedPrefix": "**REDACTED**",
        "ConnectionStateIPv6": "Bound",
        "LastConnectionErrorIPv6": "None",
        "RemoteGatewayIPv6": "fe80::ba0:bab",
    },
    "wifi": True,
    "guest_wifi": False,
    "count_wired_devices": 14,
    "count_wireless_devices": 57,
    "devices_wan_access": {
        "48:E1:E9:A2:62:67": {
            "ID": "48:E1:E9:A2:62:67",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "DC:6A:E7:1B:97:F3": {
            "ID": "DC:6A:E7:1B:97:F3",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "28:C2:DD:8C:6A:1F": {},
        "6C:0B:5E:D6:8B:B3": {
            "ID": "6C:0B:5E:D6:8B:B3",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "A4:E2:87:06:FA:09": {
            "ID": "A4:E2:87:06:FA:09",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "30:A9:DE:7E:CC:1E": {},
        "00:C3:0A:AA:98:87": {},
        "40:1C:83:3C:A0:37": {},
        "04:7B:CB:B7:D2:EE": {},
        "A0:76:4E:C4:D9:D0": {},
        "C0:4E:30:17:A0:A4": {},
        "B2:4D:45:1A:FD:F7": {},
        "0A:DF:C6:6A:5F:DA": {},
        "36:57:96:20:3E:0C": {},
        "1A:F1:31:60:BF:1B": {},
        "0E:93:50:26:D0:87": {},
        "82:10:CB:FB:CE:C0": {},
        "7A:BE:69:23:18:9A": {},
        "C2:96:1F:93:22:2E": {},
        "D2:92:96:14:16:1B": {},
        "26:98:7A:96:9F:B5": {},
        "24:FB:E3:DD:78:63": {},
        "0A:87:37:1A:42:A8": {},
        "5E:9A:02:6A:E9:A7": {},
        "3E:2F:BD:5F:0F:F5": {},
        "CA:CD:59:BC:B2:D5": {},
        "66:11:C4:6B:33:D7": {},
        "6E:B0:C3:FC:35:59": {},
        "C6:58:1E:77:1F:E0": {},
        "E4:65:B8:31:79:24": {},
        "CA:31:1F:37:5B:A5": {},
        "AE:3F:8D:FA:B9:70": {},
        "5A:57:72:3F:8B:F4": {},
        "46:21:8B:6D:23:C0": {},
        "32:DB:EF:72:06:CB": {},
        "86:D9:48:F2:E4:F0": {},
        "E6:E2:E0:A6:C0:29": {},
        "2E:26:D3:E5:54:77": {},
        "4E:47:C6:60:A1:2B": {},
        "BA:7D:05:FA:C1:A8": {},
        "72:BC:56:A7:02:31": {},
        "04:68:74:F2:14:C6": {},
        "F6:51:3A:B2:E2:91": {},
        "2E:E5:72:83:44:0F": {},
        "00:08:22:20:4F:33": {},
        "00:08:22:30:AB:FC": {},
        "00:08:22:64:22:44": {},
        "00:08:22:CC:A3:FC": {},
        "5E:36:E8:C2:70:D6": {},
        "A6:E5:E4:E6:3F:76": {},
        "BE:C2:29:B2:32:11": {},
        "CA:46:5D:32:9C:02": {},
        "68:79:C4:69:3D:C2": {},
        "00:0C:29:F1:5A:93": {},
        "D2:6F:DA:6E:02:A9": {},
        "B2:E2:C1:E2:CF:0F": {},
        "9A:91:9C:C1:2E:3A": {},
        "C8:7F:54:5D:14:9E": {
            "ID": "C8:7F:54:5D:14:9E",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "34:98:B5:A7:EC:38": {},
        "48:B0:2D:58:56:B8": {
            "ID": "48:B0:2D:58:56:B8",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "94:18:65:7D:E2:B4": {
            "ID": "94:18:65:7D:E2:B4",
            "name": "",
            "enable": True,
            "base": "Weekly",
            "def": "Enable",
            "stateMode": "Default",
            "override": "Enable",
            "temporaryOverride": False,
            "value": "Enable",
            "schedule": [],
            "device": "LOCAL",
            "target": ["LOCAL"],
        },
        "6C:FF:CE:00:88:CA": {},
        "00:0C:29:5F:94:6A": {},
        "38:7C:76:0D:2A:2F": {},
        "00:0C:29:4A:E1:83": {},
        "00:0C:29:C9:0E:C8": {},
        "00:0C:29:80:74:D7": {},
        "94:C6:91:AB:88:30": {},
        "00:0C:29:AE:D3:81": {},
        "00:E0:4D:03:82:94": {},
        "8C:9A:8F:64:9A:D8": {},
    },
    "ddns": [],
    "wifi_stats": {"RxBytes": 262695522, "TxBytes": 3604609471},
    "fiber_status": {
        "RegistrationID": "",
        "RegistrationIDIsInHexFormat": False,
        "VeipPptpUni": True,
        "MaxBitRateSupported": 10000,
        "SignalRxPower": -19546,
        "SignalTxPower": 3490,
        "Temperature": 42,
        "Voltage": 32760,
        "Bias": 18848,
        "PonMode": "GPON",
        "SerialNumber": "**REDACTED**",
        "HardwareVersion": "SMBSXLB7270300",
        "EquipmentId": "SagemcomFast5698OFR",
        "VendorId": "SMBS",
        "VendorProductCode": 0,
        "ONTSoftwareVersion0": "SAHEOFR020603",
        "ONTSoftwareVersion1": "SAHEOFR030002",
        "ONTSoftwareVersionActive": 1,
        "LowerOpticalThreshold": -35000,
        "UpperOpticalThreshold": 0,
        "LowerTransmitPowerThreshold": -1000,
        "UpperTransmitPowerThreshold": 7000,
        "Mode": "Normal",
        "CustomVendorID": "",
        "CustomEquipmentID": "",
        "VLANs": "832,835,838,840,851",
        "RogueOnu": False,
        "RogueOnuCount": 0,
        "RogueOnuLastOccurence": "0001-01-01T00:00:00Z",
        "OnuState": "O5_Operation",
        "OnuId": 11,
        "PonId": "",
        "DownstreamMaxRate": 2488320,
        "UpstreamMaxRate": 1244160,
        "DownstreamCurrRate": 2488320,
        "UpstreamCurrRate": 1244160,
        "WanMode": "",
    },
    "fiber_stats": {
        "RxPackets": 3615823,
        "TxPackets": 800210,
        "RxBytes": 4852573404,
        "TxBytes": 187871990,
        "RxErrors": 0,
        "TxErrors": 0,
        "RxDropped": 1,
        "TxDropped": 0,
        "Multicast": 1025934,
        "Collisions": 0,
        "RxLengthErrors": 0,
        "RxOverErrors": 0,
        "RxCrcErrors": 0,
        "RxFrameErrors": 0,
        "RxFifoErrors": 0,
        "RxMissedErrors": 0,
        "TxAbortedErrors": 0,
        "TxCarrierErrors": 0,
        "TxFifoErrors": 0,
        "TxHeartbeatErrors": 0,
        "TxWindowErrors": 0,
    },
    "remote_access": False,
}
