---
name: Lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v7

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run prek
        run: uv run --only-group lint prek run --all-files
